RefactoringGuru/design-patterns-typescript

src/Decorator/RealWorld/Output.txt
src/Decorator/RealWorld/index.ts
src/Facade/RealWorld/index.ts
src/Facade/RealWorld/input.txt
src/Strategy/RealWorld/Output.txt
src/Strategy/RealWorld/index.ts
tsconfig.json

In this example I want to show a simple use of the Facade pattern using an ETL process for log analytics.
The input is a simple log file and the output of the ETL process is a JSON file containing the day as key and the number of users for that day as value.

Real world examples

---

src/Composite/RealWorld/index.ts

Please accept my contribution to the Composite design pattern

add composite design pattern real world example

---

src/Bridge/RealWorld/index.ts

Please accept my contribution to the Bridge design pattern

add bridge design pattern real world example

---

src/Adapter/RealWorld/index.ts

Please accept my contribution to the Adapter design pattern

add adapter design pattern real world example

---

src/AbstractFactory/RealWorld/index.ts

Please accept my contribution to the Abstract Factory design pattern

add abstract factory example

---

src/FactoryMethod/RealWorld/index.ts

Please accept my contribution to the Factory Method design pattern

Add Factory Method example

---

src/Prototype/RealWorld/index.ts

Please accept my contribution to the Prototype design pattern

add prototype design pattern real world example

---

src/Mediator/RealWorld/Output.txt
src/Mediator/RealWorld/index.ts

Please accept this contribution to add a mediator design pattern real-world example

add mediator design pattern real world example

---

src/Command/RealWorld/Output.txt
src/Command/RealWorld/index.ts

Please accept this contribution to add a command design pattern real-world example

add command design pattern real world example

---

src/Proxy/RealWorld/Output.txt
src/Proxy/RealWorld/index.ts

Please accept my contribution to the Proxy design pattern with a real world example

add proxy design pattern real world example

---

src/Flyweight/RealWorld/Output.txt
src/Flyweight/RealWorld/index.ts

Please accept this contribution to add a flyweight design pattern real-world example

add flyweight design pattern real world example

---

src/Iterator/RealWorld/Output.txt
src/Iterator/RealWorld/index.ts

Please accept this contribution to add an iterator design pattern real-world example

Add iterator design pattern real world example

---

src/Observer/RealWorld/Output.txt
src/Observer/RealWorld/index.ts

Please accept this contribution to add an observer design pattern real-world example

add observer design pattern real world example

---

src/Memento/RealWorld/Output.txt
src/Memento/RealWorld/index.ts

Please accept this contribution to add a memento design pattern real-world example

add memento design pattern real world example

---

src/State/RealWorld/Output.txt
src/State/RealWorld/index.ts

Please accept this contribution to add an state design pattern real-world example

add state design pattern real world example

---

src/TemplateMethod/RealWorld/Output.txt
src/TemplateMethod/RealWorld/index.ts

Please accept this contribution to add a template method design pattern real-world example

add template method design pattern real world example

---

src/Singleton/Conceptual/index.ts

The method `getInstance` of `Singleton` is an implicit getter. So I upgraded it to an actual getter.

Singleton lazy loaded property getter

---

src/Singleton/Conceptual/index.ts

Some grammar and wording fixes in the documentation of the `Singleton` class and enforcing the 80 column limit.

Singleton Style and wording

---

README.md
src/Singleton/RealWorld/index.ts

I will modify this to reflect the changes in #41, if it is merged.

Provide real world example for `Singleton`

---

README.md

Once the following PRs are merged, every pattern will have a real world example.

Check the box saying all patterns have an example

---

CONTRIBUTING.md
README.md

More info:
https://github.blog/2012-09-17-contributing-guidelines/

move contributor's guide into `CONTRIBUTING.md`
